# Generated by Django 3.2 on 2021-07-19 05:21

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Kelas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namakls', models.CharField(max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Siswa',
            fields=[
                ('nisn', models.CharField(max_length=100, primary_key=True, serialize=False)),
                ('nama', models.CharField(max_length=200, null=True)),
                ('namakls', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.kelas')),
                ('user', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Spp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('spp', models.IntegerField(null=True)),
                ('bulan', models.CharField(choices=[('Januari', 'Januari'), ('Februari', 'Februari'), ('Maret', 'Maret'), ('April', 'April'), ('Mei', 'Mei'), ('Juni', 'Juni'), ('Juli', 'Juli'), ('Agustus', 'Agustus'), ('September', 'September'), ('Oktober', 'Oktober'), ('November', 'November'), ('Desember', 'Desember')], max_length=200, null=True)),
                ('tahun', models.CharField(blank=True, max_length=200, null=True)),
                ('kelas', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.kelas')),
            ],
        ),
        migrations.CreateModel(
            name='Sppsiswa',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('lunas', models.BooleanField(default=False)),
                ('url', models.CharField(blank=True, max_length=200, null=True)),
                ('siswa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.siswa')),
            ],
        ),
        migrations.CreateModel(
            name='SppItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateTimeField(auto_now_add=True)),
                ('spp', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.spp')),
                ('sppsiswa', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.sppsiswa')),
            ],
        ),
    ]
