# Generated by Django 3.2 on 2021-07-21 07:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0003_sppitem_siswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppitem',
            name='sppsiswa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='data.sppsiswa'),
        ),
    ]
