# Generated by Django 3.2 on 2021-07-21 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0004_alter_sppitem_sppsiswa'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kelas',
            name='id',
            field=models.CharField(max_length=100, primary_key=True, serialize=False),
        ),
    ]
