# Generated by Django 3.2 on 2021-07-21 18:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('data', '0005_alter_kelas_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sppitem',
            name='spp',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='data.spp'),
        ),
    ]
