# Generated by Django 3.2 on 2010-09-03 10:56

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('data', '0008_petugas'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Petugas',
            new_name='Bendahara',
        ),
    ]
